spring:
    #database
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:~/Development/sbb/local
        driver-class-name: org.h2.Driver
        username: sa
        password: 

    #jpa
    jpa:
        properties:
            hibernate: 
                dialect: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
            
      
